# Generated by Django 3.2.6 on 2021-08-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labour_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_name', models.CharField(max_length=50)),
                ('labour_city', models.CharField(max_length=300)),
                ('labour_dob', models.DateField()),
                ('labour_email', models.EmailField(max_length=254)),
                ('labour_specification', models.CharField(max_length=500)),
                ('labour_state', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
