# Generated by Django 3.2.6 on 2021-08-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='labour_detail',
            new_name='contractor_detail',
        ),
    ]
