# Generated by Django 3.2.6 on 2021-08-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0003_auto_20210818_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_detail',
            name='image',
            field=models.ImageField(default='', upload_to='labour/images'),
        ),
    ]
